/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package simulprodata.view.panels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.GregorianCalendar;
import simulprodata.controller.ViewRadioButtonListener;
import simulprodata.model.Control;
import simulprodata.model.logic.Persona;
import simulprodata.model.logic.TimeSimul;
import simulprodata.model.util.FactoryColumnModel;
import simulprodata.model.util.Notifier;
import simulprodata.model.util.TableModelData;

/**
 *
 * @author Ariel Arnedo
 */
public class PanelViewTime extends javax.swing.JPanel {

    private final Control CONTROL;
    private final TableModelData TABLEMODEL;
    
    public PanelViewTime(Control control) {
        this.CONTROL = control;
        TABLEMODEL = new TableModelData(CONTROL.getPersonasProcesadas());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panalCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePerson = new javax.swing.JTable();
        panelCola = new javax.swing.JPanel();
        panelMan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        buttonWomanNiña = new javax.swing.JButton();
        buttonWomanJoven = new javax.swing.JButton();
        buttonWomanAdulta = new javax.swing.JButton();
        buttonCaja = new javax.swing.JButton();
        buttoSalida = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        buttonManNiño = new javax.swing.JButton();
        buttonManJoven = new javax.swing.JButton();
        buttonManAdulto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelEspera = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        panalCenter.setBackground(new java.awt.Color(255, 255, 255));
        panalCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        panalCenter.setLayout(new java.awt.BorderLayout());

        tablePerson.setModel(TABLEMODEL);
        tablePerson.setColumnModel(FactoryColumnModel.createModelColumnTableMain());
        jScrollPane1.setViewportView(tablePerson);

        panalCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelCola.setBackground(new java.awt.Color(255, 255, 255));
        panelCola.setLayout(new java.awt.BorderLayout());
        panelCola.add(new PanelViewColaEnCaja(CONTROL));

        panelMan.setBackground(new java.awt.Color(255, 255, 255));
        panelMan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        buttonWomanNiña.setText("Niña");
        buttonWomanNiña.setActionCommand("Niña-Mujer");
        buttonWomanNiña.addActionListener(new ButtonListener());

        buttonWomanJoven.setText("Joven");
        buttonWomanJoven.setActionCommand("Joven-Mujer");
        buttonWomanJoven.addActionListener(new ButtonListener());

        buttonWomanAdulta.setText("Adulta");
        buttonWomanAdulta.setActionCommand("Adulta-Mujer");
        buttonWomanAdulta.addActionListener(new ButtonListener());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonWomanNiña, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(buttonWomanJoven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonWomanAdulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonWomanNiña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonWomanJoven)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonWomanAdulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonCaja.setText("Momento Abandono de Caja");
        buttonCaja.setEnabled(false);
        buttonCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCajaActionPerformed(evt);
            }
        });

        buttoSalida.setText("Momento de Salida");
        buttoSalida.setEnabled(false);
        buttoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoSalidaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        buttonManNiño.setText("Niño");
        buttonManNiño.setActionCommand("Niño-Hombre");
        buttonManNiño.addActionListener(new ButtonListener());

        buttonManJoven.setText("Joven");
        buttonManJoven.setActionCommand("Joven-Hombre");
        buttonManJoven.addActionListener(new ButtonListener());

        buttonManAdulto.setText("Adulto");
        buttonManAdulto.setActionCommand("Adulto-Hombre");
        buttonManAdulto.addActionListener(new ButtonListener());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonManAdulto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonManNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonManJoven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonManNiño)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonManJoven)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonManAdulto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulprodata/view/resources/man40x40.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulprodata/view/resources/woman40x40.png"))); // NOI18N

        javax.swing.GroupLayout panelManLayout = new javax.swing.GroupLayout(panelMan);
        panelMan.setLayout(panelManLayout);
        panelManLayout.setHorizontalGroup(
            panelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttoSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelManLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelManLayout.setVerticalGroup(
            panelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(buttonCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEspera.setBackground(new java.awt.Color(255, 255, 255));
        panelEspera.setLayout(new java.awt.BorderLayout());
        panelEspera.add(new PanelViewColaDeEspera(CONTROL));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Cola en Caja");

        jLabel4.setFont(jLabel3.getFont());
        jLabel4.setForeground(jLabel3.getForeground());
        jLabel4.setText("Cola en Atención");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelEspera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panalCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panalCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addComponent(panelMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCola, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEspera, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCajaActionPerformed
        Persona person = CONTROL.getColaDeCaja().remove();
        person.getTiempos().setMomentoDeRecepcionEnEspera(new TimeSimul(new GregorianCalendar()));
        CONTROL.getColaDeAtencion().offer(person);
        Notifier.getNotificador().notificar("Update");
        Notifier.getNotificador().notificar("UPDATE_VIEW_QUEUE");
        buttonCaja.setEnabled(!CONTROL.getColaDeCaja().isEmpty());
        buttoSalida.setEnabled(!CONTROL.getColaDeAtencion().isEmpty());
    }//GEN-LAST:event_buttonCajaActionPerformed

    private void buttoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoSalidaActionPerformed
        Persona person = CONTROL.getColaDeAtencion().remove();
        person.getTiempos().setMomentoDeSalida(new TimeSimul(new GregorianCalendar()));
        Notifier.getNotificador().notificar("Update");
        Notifier.getNotificador().notificar("UPDATE_VIEW_QUEUE");
        buttoSalida.setEnabled(!CONTROL.getColaDeAtencion().isEmpty());
    }//GEN-LAST:event_buttoSalidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoSalida;
    private javax.swing.JButton buttonCaja;
    private javax.swing.JButton buttonManAdulto;
    private javax.swing.JButton buttonManJoven;
    private javax.swing.JButton buttonManNiño;
    private javax.swing.JButton buttonWomanAdulta;
    private javax.swing.JButton buttonWomanJoven;
    private javax.swing.JButton buttonWomanNiña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panalCenter;
    private javax.swing.JPanel panelCola;
    private javax.swing.JPanel panelEspera;
    private javax.swing.JPanel panelMan;
    private javax.swing.JTable tablePerson;
    // End of variables declaration//GEN-END:variables
    
    private void enableButtonMan(boolean enable){
        buttonManNiño.setEnabled(enable);
        buttonManJoven.setEnabled(enable);
        buttonManNiño.setEnabled(enable);
    }
    
    private void enableButtonWoman(boolean enable){
        buttonWomanAdulta.setEnabled(enable);
        buttonWomanJoven.setEnabled(enable);
        buttonWomanNiña.setEnabled(enable);
    }
    
    private final class ButtonListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            Persona persona = new Persona();
            String[] values = e.getActionCommand().split("-");
            persona.setSexo(values[1]);
            persona.setTipo(values[0]);
            CONTROL.getPersonasProcesadas().add(persona);
            CONTROL.getColaDeCaja().offer(persona);
            Notifier.getNotificador().notificar("Update");
            Notifier.getNotificador().notificar("UPDATE_VIEW_QUEUE");
            buttonCaja.setEnabled(!CONTROL.getColaDeCaja().isEmpty());
        }
        
    }
    

}
