/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package simulprodata.view.panels;

import simulprodata.model.Control;
import simulprodata.model.util.FactoryCellListRenderer;
import simulprodata.model.util.chart.FactoryChartPanel;
import simulprodata.model.util.chart.Parameter;

/**
 *
 * @author Ariel Arnedo
 */
public class PanelViewChart extends javax.swing.JPanel {

    
    
    private final Control control;
    
    public PanelViewChart(Control control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChart = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listIntervals = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelChart.setBackground(new java.awt.Color(255, 255, 255));
        panelChart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelChart.setMaximumSize(new java.awt.Dimension(1200, 2147483647));
        panelChart.setMinimumSize(new java.awt.Dimension(863, 100));
        panelChart.setPreferredSize(new java.awt.Dimension(863, 100));
        panelChart.setLayout(new java.awt.BorderLayout());
        panelChart.add(FactoryChartPanel.createCharPanel(control.getPersonasProcesadas(), 4, Parameter.TIMES_AVERAGE_BETWEEN_ARRIVALS));
        add(panelChart, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(120, 0));

        listIntervals.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listIntervals.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listIntervals.setCellRenderer(FactoryCellListRenderer.createListCellRenderer());
        listIntervals.setSelectedIndex(0);
        listIntervals.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listIntervalsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listIntervals);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cantidad de Intervalos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void listIntervalsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listIntervalsValueChanged
        Runnable run = () ->{
            if(evt.getValueIsAdjusting()){
                panelChart.removeAll();
                panelChart.add(FactoryChartPanel.createCharPanel(control.getPersonasProcesadas(), (Integer)
                        Integer.parseInt(String.valueOf(listIntervals.getSelectedValue())), Parameter.TIMES_AVERAGE_BETWEEN_ARRIVALS));
                panelChart.updateUI();
            }
        };
        new Thread(run).start();
    }//GEN-LAST:event_listIntervalsValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listIntervals;
    private javax.swing.JPanel panelChart;
    // End of variables declaration//GEN-END:variables
}
